[project]
name = "dat301m"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black[jupyter]>=26.3.1",
    "gdown>=6.0.0",
    "huggingface-hub>=1.16.1",
    "ipykernel>=7.2.0",
    "kaggle>=2.2.0",
    "kagglehub>=1.0.1",
    "librosa>=0.11.0",
    "matplotlib>=3.10.9",
    "netron>=9.0.9",
    "pandas>=2.3.3",
    "pillow>=12.2.0",
    "pip>=26.1.1",
    "pyarrow>=24.0.0",
    "pydot>=4.0.1",
    "seaborn>=0.13.2",
    "tensorflow==2.17.1",
    "tensorflow-metal==1.1.0",
    "tokenizers>=0.22.2",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "transformers>=5.9.0",
    "visualkeras>=0.2.0",
]
